---
  - name: LB setup playbook 
    hosts: load-balancer
    tasks: 
      - name: install httpd
        yum:
          name: httpd
          state: present

      - name: service to be started
        service:
          name: httpd
          state: started
          enable: yes
